site_name: STM32GENERIC
docs_dir: mkdocs
pages:
- Installation: index.md
- Uploading: upload.md
- Documentation:
    - Menu options: menu_options.md
    - Arduino API: arduino_api.md
    - Arduino Standard Libraries: arduino_libraries.md
    - STM32 HAL: stm32_hal.md
- Libraries: libraries.md
- STM32 Boards:
    - Boards list: boards.md
    - Adding a board: add_board.md
    - Testnga board: test.md
    
